import { ColorArray } from '@/components/Template/PalletteColor';
import { ColorTableArray } from '@/components/Template/PalletteTable';

export const themeColors = [
  { name: 'primary', hex: '#336acc' },
  { name: 'secondary', hex: '#101e37' },
  { name: 'tertiary', hex: '#005e7a' },
  { name: 'success', hex: '#26874a' },
  { name: 'danger', hex: '#cc3333' },
  { name: 'warning', hex: '#ff9500', textDark: true },
  { name: 'info', hex: '#0086ad' },
  { name: 'light', hex: '#f3f6f9', textDark: true },
  { name: 'dark', hex: '#002733' },
];
export const yellowArray: ColorArray[] = [
  { name: '50', hex: '#FFFAE5', accessibility: 'AAA 15.88' },
  { name: '100', hex: '#fff5cc', accessibility: 'AAA 15.19' },
  { name: '200', hex: '#ffeb99', accessibility: 'AAA 13.93' },
  { name: '300', hex: '#ffe066', accessibility: 'AAA 12.75' },
  { name: '400', hex: '#ffd633', accessibility: 'AAA 11.81' },
  { name: '500', hex: '#ffcc00', accessibility: 'AAA 10.99' },
  { name: '600', hex: '#cca300', accessibility: 'AA 6.97' },
  { name: '700', hex: '#997a00', accessibility: '4.6', danger: true },
  { name: '800', hex: '#665200', accessibility: 'AAA 7.57' },
  { name: '900', hex: '#332900', accessibility: 'AAA 14.4' },
  { name: '950', hex: '#1a1500', accessibility: 'AAA 18.24' },
];
export const orangeArray: ColorArray[] = [
  { name: '50', hex: '#fff4e5', accessibility: 'AAA 15.3' },
  { name: '100', hex: '#ffeacc', accessibility: 'AAA 14.16' },
  { name: '200', hex: '#ffd599', accessibility: 'AAA 12.05' },
  { name: '300', hex: '#ffbf66', accessibility: 'AAA 10.21' },
  { name: '400', hex: '#ffaa33', accessibility: 'AAA 8.74' },
  { name: '500', hex: '#ff9500', accessibility: 'AAA 7.56' },
  { name: '600', hex: '#cc7700', accessibility: 'AA 4.91' },
  { name: '700', hex: '#995900', accessibility: 'AA 5.55' },
  { name: '800', hex: '#663c00', accessibility: 'AAA 9.49' },
  { name: '900', hex: '#331e00', accessibility: 'AAA 15.83' },
  { name: '950', hex: '#1a0f00', accessibility: 'AAA 18.88' },
];
export const redArray: ColorArray[] = [
  { name: '50', hex: '#fbefef', accessibility: 'AAA 14.8' },
  { name: '100', hex: '#f5d6d6', accessibility: 'AAA 12.25' },
  { name: '200', hex: '#ebadad', accessibility: 'AAA 8.79' },
  { name: '300', hex: '#ea8585', accessibility: 'AA 6.22' },
  { name: '400', hex: '#d65c5c', accessibility: '4.39', danger: true },
  { name: '500', hex: '#cc3333', accessibility: 'AA 5.13' },
  { name: '600', hex: '#a32929', accessibility: 'AAA 7.22' },
  { name: '700', hex: '#7a1f1f', accessibility: 'AAA 10.27' },
  { name: '800', hex: '#521414', accessibility: 'AAA 14.29' },
  { name: '900', hex: '#290a0a', accessibility: 'AAA 15.83' },
  { name: '950', hex: '#1a0f00', accessibility: 'AAA 18.88' },
];
export const purpleArray: ColorArray[] = [
  { name: '50', hex: '#f7e5ff', accessibility: 'AAA 13.94' },
  { name: '100', hex: '#f0ccff', accessibility: 'AAA 11.71' },
  { name: '200', hex: '#e299ff', accessibility: 'AAA 8.1' },
  { name: '300', hex: '#d366ff', accessibility: 'AA 5.63' },
  { name: '400', hex: '#c433ff', accessibility: '4.17', danger: true },
  { name: '500', hex: '#b600ff', accessibility: 'AA 4.74' },
  { name: '600', hex: '#9100cc', accessibility: 'AA 6.83' },
  { name: '700', hex: '#6d0099', accessibility: 'AAA 9.95' },
  { name: '800', hex: '#490066', accessibility: 'AAA 14.24' },
  { name: '900', hex: '#240033', accessibility: 'AAA 18.7' },
  { name: '950', hex: '#12001a', accessibility: 'AAA 20.18' },
];
export const blueArray: ColorArray[] = [
  { name: '50', hex: '#ecf0f9', accessibility: 'AAA 14.56' },
  { name: '100', hex: '#d9e2f2', accessibility: 'AAA 12.75' },
  { name: '200', hex: '#adc3eb', accessibility: 'AAA 9.32' },
  { name: '300', hex: '#85a5e0', accessibility: 'AA 6.69' },
  { name: '400', hex: '#5c88d6', accessibility: 'AA 4.7' },
  { name: '500', hex: '#336acc', accessibility: 'AA 5.15' },
  { name: '600', hex: '#2e569e', accessibility: 'AAA 7.14' },
  { name: '700', hex: '#274986', accessibility: 'AAA 8.81' },
  { name: '800', hex: '#1c345f', accessibility: 'AAA 12.31' },
  { name: '900', hex: '#101e37', accessibility: 'AAA 16.62' },
  { name: '950', hex: '#080f1c', accessibility: 'AAA 19.17' },
];
export const skyArray: ColorArray[] = [
  { name: '50', hex: '#e5f9ff', accessibility: 'AAA 15.3' },
  { name: '100', hex: '#ccf3ff', accessibility: 'AAA 14.11' },
  { name: '200', hex: '#99e8ff', accessibility: 'AAA 12.14' },
  { name: '300', hex: '#66dcff', accessibility: 'AAA 10.48' },
  { name: '400', hex: '#33d1ff', accessibility: 'AAA 9.26' },
  { name: '500', hex: '#00c5ff', accessibility: 'AAA 8.25' },
  { name: '600', hex: '#0086ad', accessibility: '4.18', danger: true },
  { name: '700', hex: '#005e7a', accessibility: 'AAA 7.28' },
  { name: '800', hex: '#004357', accessibility: 'AAA 10.82' },
  { name: '900', hex: '#002733', accessibility: 'AAA 15.69' },
  { name: '950', hex: '#001419', accessibility: 'AAA 18.84' },
];
export const cyanArray: ColorArray[] = [
  { name: '50', hex: '#f3fcfb', accessibility: 'AAA 15.93' },
  { name: '100', hex: '#e2f8f5', accessibility: 'AAA 15.02' },
  { name: '200', hex: '#caf2ec', accessibility: 'AAA 13.79' },
  { name: '300', hex: '#adebe2', accessibility: 'AAA 12.47' },
  { name: '400', hex: '#8de2d6', accessibility: 'AAA 11.07' },
  { name: '500', hex: '#64d8c8', accessibility: 'AAA 9.65' },
  { name: '600', hex: '#3cceb8', accessibility: 'AAA 8.48' },
  { name: '700', hex: '#2bab98', accessibility: 'AA 5.84' },
  { name: '800', hex: '#218274', accessibility: 'AA 4.65' },
  { name: '900', hex: '#10413a', accessibility: 'AAA 11.41' },
  { name: '950', hex: '#08211d', accessibility: 'AAA 16.85' },
];
export const greenArray: ColorArray[] = [
  { name: '50', hex: '#f2fbf5', accessibility: 'AAA 15.75' },
  { name: '100', hex: '#e0f8e9', accessibility: 'AAA 14.86' },
  { name: '200', hex: '#c3efd3', accessibility: 'AAA 13.15' },
  { name: '300', hex: '#94e1b0', accessibility: 'AAA 10.81' },
  { name: '400', hex: '#5eca85', accessibility: 'AAA 8.12' },
  { name: '500', hex: '#38af64', accessibility: 'AA 5.92' },
  { name: '600', hex: '#26874a', accessibility: 'AA 4.51' },
  { name: '700', hex: '#237240', accessibility: 'AA 5.91' },
  { name: '800', hex: '#205B36', accessibility: 'AAA 8.04' },
  { name: '900', hex: '#1c4b2d', accessibility: 'AAA 10.03' },
  { name: '950', hex: '#0a2915', accessibility: 'AAA 15.66' },
];
export const slateArray: ColorArray[] = [
  { name: '50', hex: '#f3f6f9', accessibility: 'AAA 15.3' },
  { name: '100', hex: '#e6ebf0', accessibility: 'AAA 16.63' },
  { name: '200', hex: '#d1d8e0', accessibility: 'AAA 11.57' },
  { name: '300', hex: '#b8c1cc', accessibility: 'AAA 9.14' },
  { name: '400', hex: '#9eaab8', accessibility: 'AAA 7.04' },
  { name: '500', hex: '#8a97a8', accessibility: 'AA 5.6' },
  { name: '600', hex: '#69788a', accessibility: 'AA 4.51' },
  { name: '700', hex: '#5c6a7a', accessibility: 'AA 5.53' },
  { name: '800', hex: '#505e70', accessibility: 'AA 6.61' },
  { name: '900', hex: '#425266', accessibility: 'AAA 7.98' },
  { name: '950', hex: '#38485c', accessibility: 'AAA 9.33' },
];
export const grayArray: ColorArray[] = [
  { name: '0', hex: '#ffffff', accessibility: 'AAA 16.63', customBorder: true, fixedWidth: false },
  { name: '50', hex: '#f2f2f2', accessibility: 'AAA 14.85', fixedWidth: false },
  { name: '100', hex: '#e5e5e5', accessibility: 'AAA 13.2', fixedWidth: false },
  { name: '200', hex: '#cccccc', accessibility: 'AAA 10.35', fixedWidth: false },
  { name: '300', hex: '#b2b2b2', accessibility: 'AAA 7.84', fixedWidth: false },
  { name: '400', hex: '#999999', accessibility: 'AA 5.84', fixedWidth: false },
  { name: '500', hex: '#8A97A8', accessibility: '4.15', danger: true, fixedWidth: false },
  { name: '600', hex: '#666666', accessibility: 'AA 5.74', fixedWidth: false },
  { name: '700', hex: '#4c4c4c', accessibility: 'AAA 8.59', fixedWidth: false },
  { name: '800', hex: '#333333', accessibility: 'AAA 12.63', fixedWidth: false },
  { name: '900', hex: '#191919', accessibility: 'AAA 17.58', fixedWidth: false },
  { name: '950', hex: '#000000', accessibility: 'AAA 21.1', fixedWidth: false },
];
export const PRINCIPALS_COLORS: ColorTableArray[] = [
  {
    base: '$blue/500',
    hex: '#336ACC',
    variable: '$primary',
    use: 'Es el color predominante de la paleta de Obelisco y se utiliza en las acciones principales.',
  },
  {
    base: '$blue/900',
    hex: '#101e37',
    variable: '$secondary',
    use: 'Se utiliza en acciones de menor importancia que las primarias y genera jerarquía dentro de la interfaz.',
  },
  {
    base: '$sky/700',
    hex: '#005E7A',
    variable: '$tertiary',
    use: 'Añade un tercer nivel de jerarquía dentro de la interfaz y se utiliza en acciones complementarias o repetitivas.',
  },
  {
    base: '$sky/600',
    hex: '#0086AD',
    variable: '$info',
    use: 'Comunica mensajes informativos y se utiliza en alertas, etiquetas y mensajes de estado.',
  },
  {
    base: '$orange/500',
    hex: '#FF9500',
    variable: '$warning',
    use: 'Comunica mensajes informativos y se utiliza en alertas, etiquetas y mensajes de estado.',
  },
  {
    base: '$green/600',
    hex: '#26874A',
    variable: '$success',
    use: 'Comunica mensajes de éxito y se utiliza en botones, alertas, etiquetas y mensajes de estado.',
  },
  {
    base: '$red/500',
    hex: '#CC3333',
    variable: '$danger',
    use: 'Comunica mensajes informativos y se utiliza en alertas, etiquetas y mensajes de estado.',
  },
  { base: '$slate/50', hex: '#F3F6F9', variable: '$light', use: 'Genera contraste con fondos oscuros.' },
  { base: '$sky/900', hex: '#002733', variable: '$danger', use: 'Genera contraste con fondos claros.' },
];
export const TEXT_COLORS: ColorTableArray[] = [
  {
    base: '$blue/900',
    hex: '#101e37',
    variable: '$body-primary',
    use: 'Color predeterminado de textos de la interfaz que garantiza legibilidad y contraste.',
  },
  {
    base: '$slate/950',
    hex: '#38485C',
    variable: '$body-secondary',
    use: 'Se utiliza para textos secundarios o de apoyo.',
  },
  {
    base: '$primary',
    hex: '#336ACC',
    variable: '$text-primary',
    use: 'Se utiliza en el texto del botón primario en la variante outlined.',
  },
  {
    base: '$secondary',
    hex: '#101e37',
    variable: '$text-secondary',
    use: 'Se utiliza en el texto del botón secundario en la variante outlined.',
  },
  {
    base: '$tertiary',
    hex: '#005E7A',
    variable: '$text-tertiary',
    use: 'Se utiliza en el texto del botón terciario en la variante outlined.',
  },
  { base: '$info', hex: '#0086AD', variable: '$text-info', use: 'Lo utilizan los íconos de información.' },
  { base: '$warning', hex: '#FF9500', variable: '$text-warning', use: 'Lo utilizan los íconos de advertencia.' },
  {
    base: '$success',
    hex: '#26874A',
    variable: '$text-success',
    use: 'Lo utilizan los íconos de éxito y el texto del botón de éxito en la variante outlined. ',
  },
  {
    base: '$danger',
    hex: '#CC3333',
    variable: '$text-danger',
    use: 'Lo utilizan los íconos de peligro y el texto del botón de peligro en la variante outlined. ',
  },
  { base: '$primary', hex: '#336ACC', variable: '$text-link', use: 'Es el color predeterminado de los enlaces.' },
  {
    base: '$slate/700',
    hex: '#5C6A7A',
    variable: '$text-placeholder',
    use: 'Se utiliza en el texto de ejemplo de un campo de formulario.',
  },
  { base: '$slate/400', hex: '#9EAAB8', variable: '$text-disabled', use: 'Es el color de los textos deshabilitados.' },
  {
    base: '$light',
    hex: '#F3F6F9',
    variable: '$text-light',
    use: 'Se utiliza en el texto del botón claro en la variante outlined.',
  },
  { base: '$dark', hex: '#002733', variable: '$text-dark', use: 'Genera contraste con fondos claros.' },
  {
    base: '$grayscale/0',
    hex: '#FFFFFF',
    variable: '$text-white',
    use: 'Genera contraste con fondos oscuros.',
    customBorder: true,
  },
  { base: '$grayscale/950', hex: '#000000', variable: '$text-black', use: 'Genera contraste con fondos claros.' },
];
export const STATES_COLORS: ColorTableArray[] = [
  { base: '$blue/700', hex: '#274986', variable: '$hover', use: 'Color predeterminado para componentes en hover.' },
  { base: '$cyan/800', hex: '#218274', variable: '$focused', use: 'Se utiliza para el indicador del estado en foco.' },
  {
    base: '$blue/700',
    hex: '#274986',
    variable: '$active',
    use: 'Se utiliza para los estados activos de los componentes (seleccionado, desplegado, expandido, etc.).',
  },
  {
    base: '$purple/700',
    hex: '#6D0099',
    variable: '$visited',
    use: 'Es el color para los enlaces visitados sobre fondos claros.',
  },
  {
    base: '$purple/200',
    hex: '#E299FF',
    variable: '$visited-ondark',
    use: 'Es el color para los enlaces visitados sobre fondos oscuros.',
  },
  {
    base: '$slate/100',
    hex: '#E6EBF0',
    variable: '$disabled',
    use: 'Es el color de fondo de componentes deshabilitados sobre fondos claros.',
  },
  {
    base: '$slate/700',
    hex: '#5C6A7A',
    variable: '$disabled-ondark',
    use: 'Es el color de fondo de componentes deshabilitados sobre fondos oscuros.',
  },
  {
    base: '$red/800',
    hex: '#521414',
    variable: '$focused-error',
    use: 'Se utiliza para el indicador del estado en foco del botón de peligro.',
  },
  {
    base: '$grayscale/0',
    hex: '#FFFFFF',
    variable: '$focused-ondark',
    use: 'Se utiliza para el indicador del estado en foco de enlaces sobre fondos oscuros.',
    customBorder: true,
  },
];
export const BORDER_COLORS: ColorTableArray[] = [
  {
    base: '$slate/100',
    hex: '#F3F6F9',
    variable: '$border-neutral',
    use: 'Es el color predeterminado de todos los bordes de componentes y divisores.',
  },
  { base: '$primary', hex: '#336ACC', variable: '$border-link', use: 'Es el color del subrayado para los enlaces.' },
];
export const BACKGROUND_COLORS: ColorTableArray[] = [
  {
    base: '$grayscale/0',
    hex: '#ffffff',
    variable: '$bg-white',
    use: 'Color de fondo predeterminado de una página.',
    customBorder: true,
  },
  {
    base: '$sky/900',
    hex: '#002733',
    variable: '$bg-dark',
    use: 'Se utiliza en componentes de fondo oscuro como el footer, el tooltip y el banner.',
  },
  {
    base: '$light',
    hex: '#F3F6F9',
    variable: '$bg-lightest',
    use: 'Se utiliza para el fondo de los encabezados de página y para generar contraste con fondos claros en algunos componentes.',
  },
  {
    base: '$slate/100',
    hex: '#E6EBF0',
    variable: '$bg-lighter',
    use: 'Se utiliza como fondo del banner claro y de pestañas. ',
  },
  {
    base: '$slate/200',
    hex: '#D1D8E0',
    variable: '$bg-light',
    use: 'Se utiliza como fondo de la barra de progreso y del switch. ',
  },
];
export const ALERT_COLORS: ColorTableArray[] = [
  { base: '$sky/50', hex: '#E5F9FF', variable: '$bg-info', use: 'Es el color de fondo de las alertas de información.' },
  {
    base: '$orange/50',
    hex: '#FFF4E5',
    variable: '$bg-warning',
    use: 'Es el color de fondo de las alertas de advertencia.',
  },
  { base: '$green/50', hex: '#F2FBF5', variable: '$bg-success', use: 'Es el color de fondo de las alertas de éxito.' },
  { base: '$red/50', hex: '#FBEFEF', variable: '$bg-danger', use: 'Es el color de fondo de las alertas de peligro.' },
  {
    base: '$info',
    hex: '#0086ad',
    variable: '$border-info',
    use: 'Es el color del borde de las alertas de información.',
  },
  {
    base: '$warning',
    hex: '#FF9500',
    variable: '$border-warning',
    use: 'Es el color del borde de las alertas de advertencia.',
  },
  {
    base: '$success',
    hex: '#26874A',
    variable: '$border-success',
    use: 'Es el color del borde de las alertas de éxito.',
  },
  {
    base: '$danger',
    hex: '#CC3333',
    variable: '$border-danger',
    use: 'Es el color del borde de las alertas de peligro.',
  },
];
export const SCROLL_COLORS: ColorTableArray[] = [
  {
    base: '$text-disabled',
    hex: '#9EAAB8',
    variable: '$indicator',
    use: 'Es el color del indicador de la barra de desplazamiento.',
  },
];
export const PROGRESS_COLORS: ColorTableArray[] = [
  {
    base: '$primary',
    hex: '#336ACC',
    variable: '$blue',
    use: 'Es el color del indicador de progreso de la variante azul del componente. ',
  },
  {
    base: '$success',
    hex: '#26874A',
    variable: '$green',
    use: 'Es el color del indicador de progreso de la variante verde del componente.',
  },
];
export const BUTTON_COLORS: ColorTableArray[] = [
  {
    base: '$primary',
    hex: '#336ACC',
    variable: '$primary/bg-default',
    use: 'Es el color de fondo del botón primario.',
  },
  {
    base: '$blue/600',
    hex: '#2E569E',
    variable: '$primary/bg-hover',
    use: 'Es el color de fondo del botón primario en el estado hover.',
  },
  {
    base: '$primary',
    hex: '#336ACC',
    variable: '$primary/border-outlined',
    use: 'Es el color del borde del botón primario en su variante outlined.',
  },
  {
    base: '$secondary',
    hex: '#101e37',
    variable: '$secondary/bg-default',
    use: 'Es el color de fondo del botón secundario.',
  },
  {
    base: '$blue/950',
    hex: '#080F1C',
    variable: '$secondary/bg-hover',
    use: 'Es el color de fondo del botón secundario en el estado hover.',
  },
  {
    base: '$secondary',
    hex: '#101E37',
    variable: '$secondary/border-outlined',
    use: 'Es el color del borde del botón secundario en su variante outlined.',
  },
  {
    base: '$tertiary',
    hex: '#005E7A',
    variable: '$tertiary/bg-default',
    use: 'Es el color de fondo del botón terciario.',
  },
  {
    base: '$blue/950',
    hex: '#004357',
    variable: '$tertiary/bg-hover',
    use: 'Es el color de fondo del botón terciario en el estado hover.',
  },
  {
    base: '$tertiary',
    hex: '#005E7A',
    variable: '$tertiary/border-outlined',
    use: 'Es el color del borde del botón terciario en su variante outlined.',
  },
  { base: '$bg-lightest', hex: '#F3F6F9', variable: '$light/bg-default', use: 'Es el color de fondo del botón claro.' },
  {
    base: '$bg-light',
    hex: '#D1D8E0',
    variable: '$light/bg-hover',
    use: 'Es el color de fondo del botón claro en el estado hover.',
  },
  {
    base: '$light',
    hex: '#F3F6F9',
    variable: '$light/border-outlined',
    use: 'Es el color del borde del botón claro en su variante outlined.',
  },
  {
    base: '$success',
    hex: '#26874A',
    variable: '$success/bg-default',
    use: 'Es el color de fondo del botón de éxito.',
  },
  {
    base: '$green/700',
    hex: '#237240',
    variable: '$success/bg-hover',
    use: 'Es el color de fondo del botón de éxito en el estado hover.',
  },
  {
    base: '$success',
    hex: '#26874A',
    variable: '$success/border-outlined',
    use: 'Es el color del borde del botón de éxito en su variante outlined.',
  },
  {
    base: '$danger',
    hex: '#CC3333',
    variable: '$danger/bg-default',
    use: 'Es el color de fondo del botón de peligro.',
  },
  {
    base: '$red/700',
    hex: '#7A1F1F',
    variable: '$danger/bg-hover',
    use: 'Es el color de fondo del botón de peligro en el estado hover.',
  },
  {
    base: '$danger',
    hex: '#CC3333',
    variable: '$danger/border-outlined',
    use: 'Es el color del borde del botón de peligro en su variante outlined.',
  },
];
export const CALENDAR_COLORS: ColorTableArray[] = [
  {
    base: '$bg-default',
    hex: '#336ACC',
    variable: 'bg-default',
    use: 'Es el color de fondo del calendario y las filas del calendario por defecto.',
  },
  {
    base: '$bg-secondary',
    hex: '#2E569E',
    variable: '$bg-secondary',
    use: 'Es el color de fondo secundario de las filas del calendario.',
  },
  {
    base: '$primary',
    hex: '#336ACC',
    variable: '$day-item/$bg-primary',
    use: 'Es el color del borde del botón primario en su variante outlined.',
  },
  {
    base: '$blue/600',
    hex: '#2E569E',
    variable: '$day-item/$bg-primary-hover',
    use: 'Es el color de hover del fondo primario de un día seleccionado.',
  },
  {
    base: '$secondary',
    hex: '#101E37',
    variable: '$day-item/$bg-secondary',
    use: 'Es el color de fondo secundario de las filas del calendario.',
  },
  {
    base: '$blue/950',
    hex: '#080F1C',
    variable: '$day-item/$bg-secondaryhover',
    use: 'Es el color de hover del fondo secundario de un día seleccionado.',
  },
];
export const BLOCKQUOTE_COLORS: ColorTableArray[] = [
  {
    base: '$body-primary',
    hex: '#101E37',
    variable: '$mark',
    use: 'Es el color de la línea de cita dentro del componente.',
  },
];
export const BADGE_COLORS: ColorTableArray[] = [
  { base: '$sky/50', hex: '#E5F9FF', variable: '$bg-info', use: 'Es el color de fondo de la etiqueta de información.' },
  {
    base: '$orange/50',
    hex: '#FFF4E5',
    variable: '$bg-warning',
    use: 'Es el color de fondo de la etiqueta de advertencia.',
  },
  { base: '$green/50', hex: '#F2FBF5', variable: '$bg-success', use: 'Es el color de fondo de la etiqueta de éxito.' },
  { base: '$red/50', hex: '#FBEFEF', variable: '$bg-danger', use: 'Es el color de fondo de la etiqueta de peligro.' },
  {
    base: '$text/body-secondary',
    hex: '#38485C',
    variable: '$border-primary',
    use: 'Es el color del borde de la etiqueta predeterminada.',
  },
  {
    base: '$info',
    hex: '#0086ad',
    variable: '$border-info',
    use: 'Es el color del borde de la etiqueta de información.  ',
  },
  {
    base: '$warning',
    hex: '#FF9500',
    variable: '$border-warning',
    use: 'Es el color del borde de la etiqueta de advertencia.',
  },
  {
    base: '$success',
    hex: '#26874A',
    variable: '$border-success',
    use: 'Es el color del borde de la etiqueta de éxito.',
  },
  {
    base: '$danger',
    hex: '#CC3333',
    variable: '$border-danger',
    use: 'Es el color del borde de la etiqueta de peligro.',
  },
];
export const LINK_COLORS: ColorTableArray[] = [
  {
    base: '$text-white',
    hex: '#FFFFFF',
    variable: '$text-ondark',
    use: 'Es el color de texto del enlace sobre fondos oscuros.',
    customBorder: true,
  },
  {
    base: '$text-white',
    hex: '#FFFFFF',
    variable: '$border-ondark',
    use: 'Es el color del subrayado del enlace sobre fondos oscuros.',
    customBorder: true,
  },
  {
    base: '$visited',
    hex: '#6D0099',
    variable: '$text-visited',
    use: 'Es el color para los enlaces visitados sobre fondos claros. ',
  },
  {
    base: '$visited',
    hex: '#6D0099',
    variable: '$border-visited',
    use: 'Es el color del subrayado del estado visitado del enlace sobre fondos claros.',
  },
  {
    base: '$visited-ondark',
    hex: '#E299FF',
    variable: '$text-visited-ondark',
    use: 'Es el color para los enlaces visitados sobre fondos oscuros. ',
  },
  {
    base: '$visited-ondark',
    hex: '#E299FF',
    variable: '$border-visited-ondark',
    use: 'Es el color del subrayado del estado visitado del enlace sobre fondos oscuros.',
  },
];
export const SPINNER_COLORS: ColorTableArray[] = [
  {
    base: '$bg-light',
    hex: '#D1D8E0',
    variable: '$bg',
    use: 'Es el color del fondo del spinner sobre fondos claros. ',
  },
  {
    base: '$slate/400',
    hex: '#9EAAB8',
    variable: '$bg-ondark',
    use: 'Es el color del fondo del spinner sobre fondos oscuros. ',
  },
  {
    base: '$text-primary',
    hex: '#336ACC',
    variable: '$indicator-primary',
    use: 'Es el color del indicador del spinner primario.',
  },
  {
    base: '$text-secondary',
    hex: '#101e37',
    variable: '$indicator-secondary',
    use: 'Es el color del indicador del spinner secundario.',
  },
  {
    base: '$text-tertiary',
    hex: '#005E7A',
    variable: '$indicator-tertiary',
    use: 'Es el color del indicador del spinner terciario.',
  },
  {
    base: '$text-success',
    hex: '#26874A',
    variable: '$indicator-success',
    use: 'Es el color del indicador del spinner de éxito.',
  },
  {
    base: '$text-danger',
    hex: '#CC3333',
    variable: '$indicator-danger',
    use: 'Es el color del indicador del spinner de peligro.',
  },
  {
    base: '$text-light',
    hex: '#F3F6F9',
    variable: '$indicator-light',
    use: 'Es el color del indicador del spinner claro.',
  },
  {
    base: '$text-dark',
    hex: '#002733',
    variable: '$indicator-dark',
    use: 'Es el color del indicador del spinner oscuro.',
  },
];
export const FOOTER_COLORS: ColorTableArray[] = [
  {
    base: '$body-secondary',
    hex: '#38485C',
    variable: '$section-divider',
    use: 'Es el color de la línea divisoria de secciones dentro del footer. ',
  },
];
